### ISSUE TITLE
Add operator extra link for Data Docs in the `GreatExpectationsOperator`

### ISSUE THREAD

**Issue by josh-fell** [astronomer/airflow-provider-great-expectations#48]
In Airflow, there is a feature which allows for external links to be present as buttons on the Task Instance modal in the Airflow UI called an [operator extra link](https://airflow.apache.org/docs/apache-airflow/stable/howto/define_extra_link.html). This feature is really useful to directly navigate from the Airflow UI to an external site which may be for monitoring a third-party execution that Airflow just triggered, handy documentation, etc.

IMO linking to Data Docs directly from a `GreatExpectationsOperator` task would be really beneficial to users and increase the holistic visibility that's available at their fingertips.

**Comment by josh-fell** [comment]
The easiest, and the most widely-used, way to get that data into an operator link is via `XCom`. If you can push a URL to `XCom` or whatever values would be needed to build the URL string, you can have the `get_link()` method that would be overwritten to return the URL.

For some examples, check out [Azure Data Factory](https://github.com/apache/airflow/blob/e1a42c4fc8a634852dd5ac5b16cade620851477f/airflow/providers/microsoft/azure/operators/data_factory.py#L33-L73) and [dbt Cloud](https://github.com/apache/airflow/blob/e1a42c4fc8a634852dd5ac5b16cade620851477f/airflow/providers/dbt/cloud/operators/dbt.py#L28-L45) providers. Then in the `GreatExpectationOperator` you can add the link as attribute. Something like:

```python
class GreatExpectationsOperator:
    ...
    operator_extra_links = (DataDocsLink(),)

    ...
    def __init__(...):

```

There is some [Airflow documentation](https://airflow.apache.org/docs/apache-airflow/stable/howto/define_extra_link.html) on creating these operator extra links too.

**Comment by denimalpaca** [comment]
Completed in `0.2.0`
