### ISSUE TITLE
`GreatExpectationsOperator` fails when run validations agains `Athena` and work correct against `Redshift`

### ISSUE THREAD

**Issue by guidoturtu** [astronomer/airflow-provider-great-expectations#49]
### Overview
`GreatExpectationsOperator` fails when run validations agains `Athena` and work correct against `Redshift`

### Conditions
`docker-compose` airflow
airflow==2.2.3
airflow-provider-great-expectations==0.1.3
great-expectations==0.14.7

### Procedure
- Created a DAG that run validations inside AWS environment with `SqlAlchemyEngine`.
- Defined both `datasources` identically, just change the connection string / credentials.
- Run the same operator with both same configurations.

### Problems found
- DataDoc on the slack notification, never shown.
    - Neither with the modification of `notify_with`: ["all" | "local_site" | None]  
    ![image](https://user-images.githubusercontent.com/48365565/155895979-30139f6b-2fce-4630-92cb-fc5e8ff30b03.png)
- Athena validations never executed correctly
```bash
"exception_info": {
  "exception_traceback": "Traceback (most recent call last):\n  File \"/home/***/.local/lib/python3.7/site-packages/great_expectations/execution_engine/execution_engine.py\", line 397, in resolve_metrics\n    new_resolved = self.resolve_metric_bundle(metric_fn_bundle)\n  File \"/home/***/.local/lib/python3.7/site-packages/great_expectations/execution_engine/sqlalchemy_execution_engine.py\", line 815, in resolve_metric_bundle\n    domain_kwargs=domain_kwargs,\n  File \"/home/***/.local/lib/python3.7/site-packages/great_expectations/execution_engine/sqlalchemy_execution_engine.py\", line 505, in get_domain_records\n    selectable = selectable.columns().subquery()\nAttributeError: 'TextAsFrom' object has no attribute 'subquery'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/***/.local/lib/python3.7/site-packages/great_expectations/validator/validator.py\", line 845, in resolve_validation_graph\n    runtime_configuration=runtime_configuration,\n  File \"/home/***/.local/lib/python3.7/site-packages/great_expectations/validator/validator.py\", line 1749, in _resolve_metrics\n    runtime_configuration=runtime_configuration,\n  File \"/home/***/.local/lib/python3.7/site-packages/great_expectations/execution_engine/execution_engine.py\", line 401, in resolve_metrics\n    message=str(e), failed_metrics=[x[0] for x in metric_fn_bundle]\ngreat_expectations.exceptions.exceptions.MetricResolutionError: 'TextAsFrom' object has no attribute 'subquery'\n",
  "exception_message": "'TextAsFrom' object has no attribute 'subquery'",
  "raised_exception": true
}
``` 
> While `Redshift with the exact same configurations, runs OK.

### Additional information for the issue
- When we was developing these procedure with a Lambda, Athena `RuntimeBatchRequest` query need to be between `( )` to work.
```python
"query": f"(select * from db.table limit 100)"
```
- Before these last version of a DAG; we was creation a `RuntimeBatchRequest` by code, and pushing as a parameter for the checkpoint. This create the **EXACTLY SAME ERROR** as Athena now.

### File reference
DAG gist file for reference (modified / deleted confidential information): [dag_poc.py](https://gist.github.com/guidoturtu/d909e7d83ab797db4a5aeeb78fd8cbc1)

**Comment by denimalpaca** [comment]
Closing this -- there are known issues with GX and Athena and this likely has nothing to do with the operator.
