### ISSUE TITLE
Missing `template_fields` in operator

### ISSUE THREAD

**Issue by blazej-fetcherr** [astronomer/airflow-provider-great-expectations#60]
Is:
https://github.com/astronomer/airflow-provider-great-expectations/blob/577172b52330770858cd754a03d586387e110606/great_expectations_provider/operators/great_expectations.py#L118
Should be:
https://github.com/astronomer/airflow-provider-great-expectations/blob/f1621f29b58615b5adcd39698eb02e06d9021135/great_expectations_provider/operators/great_expectations.py#L58

Somebody removed the `template_fields` declaration for the operator, **which basically makes the operator useless**. Please fix that ASAP and COVER it with unit tests to prevent such situation from happening in the future.

**Comment by grozail** [comment]
Experiencing the same issue

**Comment by denimalpaca** [comment]
Hi @blazej-fetcherr , I can push a fix and release shortly. So you know, the `batch_kwargs` and `assets_to_validate` parameters no longer exist in the operator, so any reference to those should be removed. Please take a look at the new list of [parameters](https://github.com/astronomer/airflow-provider-great-expectations/blob/main/great_expectations_provider/operators/great_expectations.py#L80).

**Comment by blazej-fetcherr** [comment]
Hi @denimalpaca,
actually I think that @grozail pointed everybody to more up to date version of this line 😄
I was in a hurry before my Sprint demo so I just pointed to a first `template_fields` example which I could find. Maybe it was a bit inaccurate but I have a ton of my own bugs to fix 😆

**Comment by denimalpaca** [comment]
You'll see the PR implements the fields @grozail pointed out a few new ones.

**Comment by denimalpaca** [comment]
@blazej-fetcherr @grozail [0.2.1](https://pypi.org/project/airflow-provider-great-expectations/0.2.1/) has just been released with the fix.

**Comment by grozail** [comment]
Thank you for collaboration and quick response!
