### ISSUE TITLE
Feature request: Add templating for attribute dataframe_to_validate.

### ISSUE THREAD

**Issue by rbthomp** [astronomer/airflow-provider-great-expectations#76]
I'm wondering if we can add `dataframe_to_validate` as a templated field? 

```
 template_fields = (
      "run_name",
      "conn_id",
      "data_context_root_dir",
      "checkpoint_name",
      "checkpoint_kwargs",
      "query_to_validate",
    )
```

https://github.com/astronomer/airflow-provider-great-expectations/blob/main/great_expectations_provider/operators/great_expectations.py#L118

**Comment by kaxil** [comment]
`dataframe_to_validate` can't be templated as it will contain the actual dataframe object.

Templating can only be done of primitive classes or arbitrary classes who has a "template" class/instance variable.

Source: https://github.com/apache/airflow/blob/35ad16dc0f6b764322b1eb289709e493fbbb0ae0/airflow/template/templater.py#L151-L173
