### ISSUE TITLE
add support for Athena (aws_default) airflow connection

### ISSUE THREAD

**Issue by diman82** [astronomer/airflow-provider-great-expectations#90]
There is even a [TODO comment](https://github.com/astronomer/airflow-provider-great-expectations/blob/main/great_expectations_provider/operators/great_expectations.py#L271) in operator code for adding support for Athena connection.
Can you please add support for this?

**Comment by diman82** [comment]
Hey @denimalpaca.
Sure, I can help with testing!

**Comment by denimalpaca** [comment]
@diman82 please see the PR linked!

**Comment by lionsdwarf** [comment]
> There is even a [TODO comment](https://github.com/astronomer/airflow-provider-great-expectations/blob/main/great_expectations_provider/operators/great_expectations.py#L271) in operator code for adding support for Athena connection. Can you please add support for this?

Here's the [permalink](https://github.com/astronomer/airflow-provider-great-expectations/blob/c4aae5b0728726d0881de4143087e0b6ae3c6224/great_expectations_provider/operators/great_expectations.py#L281) instead

**Comment by denimalpaca** [comment]
Hey @lionsdwarf , PR #91 is open with this addition. I don't have access to Athena and can't test, however, so I'm just waiting for @diman82 or someone else to test the fix before I do a merge and release. If you'd like to help, we can close this issue out this week!

**Comment by lionsdwarf** [comment]
We are interested in Trino support, which is also mentioned in the TODO comment. 

I was curious if the recent upgrade to the core gx library to use database connection strings (instead of config parameters) would solve this problem, but it looks to me like the provider is already using the latest core version.

**Comment by denimalpaca** [comment]
Could you please open a separate issue for Trino support? I can look into opening another PR, but as I don't have access to Trino either, I'd need someone else to test it before I merge.

This and the Athena support is _only_ for the default datasource being built; you can still use this operator with Trino _now_ if you are supplying a checkpoint and have your datasources configured in the data context config.
